---
Name: app
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

SilverStripe\View\SSViewer:
  themes:
    - '$default'
    - sun

SilverStripe\Control\Email\Email:
  admin_email: info@sunnysideup.co.nz

SilverStripe\i18n\i18n:
  locale: en_NZ
  date_format: dd-MM-YYYY

SilverStripe\Admin\LeftAndMain:
  application_name: 'Campaign Monitor Demo'

Sunnysideup\WebpackRequirementsBackend\Api\Configuration:
  webpack_theme: sun

# UTF8MB4 has limited support in older MySQL versions.
# Remove this configuration if you experience issues.
---
Name: myproject-database
---
SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_unicode_ci
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
